config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :photos do
      get 'library', :on => :collection
      post 'mass_destroy', :on => :collection
    end
    resources :photo_albums
    resources :photo_galleries
  end

  scope Spud::Photos.config.base_path do
    if Spud::Photos.config.galleries_enabled
      resources :photo_galleries, :only => :index, :path => '/' do
        resources :photo_albums, :only => [:index, :show], :path => '/'
      end
    else
      resources :photo_albums, :only => [:index, :show], :path => '/'
    end
  end

end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::ApplicationController

  include RespondsToParent
  belongs_to_spud_app :photo_albums

  before_filter :get_photo, :only => [:show, :edit, :update, :destroy]
  layout false

  def index
    @photos = SpudPhoto.all
    respond_with @photos
  end

  def show
    respond_with @photo
  end

  def new
    @photo = SpudPhoto.new
    respond_with @photo do |format|
      format.js { render 'new', :layout => false }
    end
  end

  def create
    photo_file = photo_params[:photo]
    if photo_file.present?
      fingerprint = Digest::MD5.hexdigest(photo_file.read)
      photo_file.rewind
      @photo = SpudPhoto.where(:photo_fingerprint => fingerprint).first
    end
    
    if @photo.blank?
      @photo = SpudPhoto.new(photo_params)
    end

    if @photo.save
      success = true
      flash[:notice] = 'SpudPhoto created successfully' 
    end
    if request.xhr?
      render json_for_photo(success)
    else
      respond_to_parent do
        render 'show.js'
      end
    end
  end

  def edit
    respond_with @photo do |format|
      format.js { render 'edit', :layout => false }
    end
  end
  
  def update
    @photo.update_attributes(photo_params)
    if @photo.save
      success = true
      flash[:notice] = 'SpudPhoto updated successfully' 
    end
    if request.xhr?
      render json_for_photo(success)
    else
      respond_to_parent do
        render 'show.js'
      end
    end
  end

  def destroy
    flash[:notice] = 'SpudPhoto deleted successfully' if @photo.destroy
    respond_with @photo, :location => admin_photos_path
  end

  def mass_destroy
    @photos = SpudPhoto.where(:id => params[:spud_photo_ids])
    flash[:notice] = 'Photos deleted successfully' if @photos.destroy_all
    respond_with @photos, :location => admin_photos_path
  end

private

  def get_photo
    @photo = SpudPhoto.find(params[:id])
  end
  
  def json_for_photo(success)
    if success
      return {:status => 200, :json => { 
        :id => @photo.id, 
        :html => render_to_string(:partial => 'photo', :locals => {:photo => @photo}, :layout => nil)
      }}
    else
      return {:status => 422, :json => {
        :id => 0,
        :html => render_to_string(:partial => 'form', :layout => nil)
      }}
    end
  end

  def photo_params
    params.require(:spud_photo).permit(:title, :caption, :photo)
  end

end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper

  def photo_is_selected
    return (@photo_album && @photo_album.photo_ids.include?(photo.id))
  end

end

app/views/admin/photos/_form.html.erb
<%= form_for @photo, :url => (@photo.new_record? ? admin_photos_path : admin_photo_path(@photo)), :builder => TbCore::FormBuilder, :html => {:id => 'admin-photo-form', :target => 'admin-photo-form_target', :class => 'form-horizontal'} do |f| %> 
  
  <%= tb_form_errors(f.object) %>
  
  <fieldset>
    <legend>Photo Info</legend>  
      <%= f.tb_text_field :title %>
      <%= f.tb_text_field :caption %>
  </fieldset>

  <fieldset>
    <legend id="fileUploadSizeLegend">File Upload</span></legend>
      <span class="help-block admin-photo-form-max-size"></span>
      <%= f.tb_file_field :photo %>
      <% unless @photo.new_record? %>
        <%= f.tb_input_field 'Current Photo' do %>
          <%= image_tag @photo.photo.url(:spud_admin_medium), :class => 'admin-photo-form-current-photo' %>
        <% end %>
      <% end %>
  </fieldset>

  <iframe id="admin-photo-form_target" name="admin-photo-form_target" style="display:none;"></iframe>

<% end %>

app/views/admin/photos/_photo.html.erb
<%= content_tag :div, 
  :rel => photo.id,
  :id => "admin-photo-#{photo.id}", 
  :style => "background-image:url('#{photo.photo.url(:spud_admin_small)}')",
  :class => "admin-photo-ui-thumb admin-photo-ui-thumb-small admin-photo" do %>
  <div style="display:none;">
    <%= hidden_field_tag 'spud_photo_album[photo_ids][]', photo.id %>
  </div>
  <div class="admin-photo-ui-thumb-controls">
    <%= link_to '', edit_admin_photo_path(photo), :class => 'admin-photos-btn-edit' %>
    <%= link_to '', '#', :class => 'admin-photos-btn-remove' %>
  </div>
<% end %>

app/views/admin/photos/destroy.js.erb
spud.admin.photos.markPhotoAsDeleted(<%= @photo.id %>);

app/views/admin/photos/edit.html.erb
<%= render :partial => 'form' %>

app/views/admin/photos/index.html.erb
<div id="admin-photo-library" class="admin-photo-ui-thumbs admin-photo-ui-thumbs-selectable">
  <%= render :partial => 'photo', :collection => @photos %>
<div>

app/views/admin/photos/new.html.erb
<%= render :partial => 'form' %>

app/views/admin/photos/show.js.erb
<% if @photo.errors.any? %>
  spud.admin.photos.photoLegacyUploadErrors("<%= escape_javascript(render 'form') %>");
<% else %>
  spud.admin.photos.photoLegacyUploadComplete(<%= @photo.id %>, "<%= escape_javascript(render :partial => 'photo', :locals => {:photo => @photo}) %>");
<% end %>