config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :photos do
      get 'library', :on => :collection
      post 'mass_destroy', :on => :collection
    end
    resources :photo_albums
    resources :photo_galleries
  end

  scope Spud::Photos.config.base_path do
    if Spud::Photos.config.galleries_enabled
      resources :photo_galleries, :only => :index, :path => '/' do
        resources :photo_albums, :only => [:index, :show], :path => '/'
      end
    else
      resources :photo_albums, :only => [:index, :show], :path => '/'
    end
  end

end

app/models/spud_photo.rb
class SpudPhoto < ActiveRecord::Base

  extend ActionView::Helpers::NumberHelper

  has_many :spud_photo_albums_photos, :dependent => :destroy
  has_many :albums,
    :through => :spud_photo_albums_photos,
    :source => :spud_photo_album

  has_attached_file :photo, 
    :styles => lambda { |attachment| attachment.instance.dynamic_styles },
    :convert_options => Spud::Photos.convert_options,
    :source_file_options => Spud::Photos.source_file_options,
    :storage => Spud::Photos.paperclip_storage,
    :s3_credentials => Spud::Photos.s3_credentials,
    :url => Spud::Photos.storage_url,
    :path => Spud::Photos.storage_path

  validates_attachment :photo,
    :presence => true,
    :content_type => {:content_type => ['image/jpg', 'image/jpeg', 'image/png']},
    :size => {
      :less_than => Spud::Photos.max_image_upload_size,
      :message => "size cannot exceed " + number_to_human_size(Spud::Photos.max_image_upload_size), 
      :if => Proc.new{|p| Spud::Photos.max_image_upload_size > 0}
    }

  def dynamic_styles
    admin_styles = {
      :spud_admin_small => {:geometry => '125x125#', :format => :jpg, :source_file_options => '-density 72', :convert_options => '-strip -quality 85'},
      :spud_admin_medium => {:geometry => '300x200', :format => :jpg, :source_file_options => '-density 72', :convert_options => '-strip -quality 85'}
    }
    return admin_styles.merge(Spud::Photos.config.photo_styles)
  end

end

app/controllers/admin/photo_galleries_controller.rb
class Admin::PhotoGalleriesController < Admin::ApplicationController

  before_filter :get_gallery, :only => [:show, :edit, :update, :destroy]
  before_filter :get_albums, :only => [:new, :create, :edit, :update]
  add_breadcrumb 'Photo Galleries', :admin_photo_galleries_path
  layout 'admin/spud_photos'
  belongs_to_spud_app :photo_galleries

  def index
    @photo_galleries = SpudPhotoGallery.all
    respond_with @photo_galleries
  end
  
  def show
    respond_with @photo_gallery
  end
  
  def new
    @photo_gallery = SpudPhotoGallery.new
    respond_with @photo_gallery
  end
  
  def create
    @photo_gallery = SpudPhotoGallery.new(photo_gallery_params)
    flash[:notice] = 'Gallery created successfully' if @photo_gallery.save
    respond_with @photo_gallery, :location => admin_photo_galleries_path
  end
  
  def edit
    respond_with @photo_gallery
  end
  
  def update
    @photo_gallery.update_attributes(photo_gallery_params)
    flash[:notice] = 'Gallery updated successfully' if @photo_gallery.save
    respond_with @photo_gallery, :location => admin_photo_galleries_path
  end
  
  def destroy
    flash.now[:notice] = 'Gallery deleted successfully' if @photo_gallery.destroy
    respond_with @photo_gallery, :location => admin_photo_galleries_path
  end

private

  def get_gallery
    @photo_gallery = SpudPhotoGallery.find(params[:id])
  end

  def get_albums
    @photo_albums = SpudPhotoAlbum.all
  end

  def photo_gallery_params
    params.require(:spud_photo_gallery).permit(:title, :url_name, :album_ids => [])
  end

end

app/controllers/photo_galleries_controller.rb
class PhotoGalleriesController < ApplicationController

  respond_to :html, :json, :xml
  layout Spud::Photos.base_layout

  def index
    @photo_galleries = SpudPhotoGallery.ordered
    respond_with @photo_galleries
  end

end

app/helpers/admin/photo_galleries_helper.rb
module Admin::PhotoGalleriesHelper
end

app/helpers/photo_galleries_helper.rb
module PhotoGalleriesHelper
end

app/views/admin/photo_galleries/_album.html.erb
<div id="admin-photo-album-<%= album.id %>" class="admin-photo-ui-thumb" style="background-image:url('<%= album.top_photo_url(:spud_admin_small) %>')">
  <h5><%= album.title %></h5>
  <div style="display:none;">
    <%= hidden_field_tag 'spud_photo_gallery[album_ids][]', album.id %>
  </div>
  <div class="admin-photo-ui-thumb-controls">
    <%= link_to '', '#', :class => 'admin-photos-btn-delete' %>
  </div>
</div>

app/views/admin/photo_galleries/_form.html.erb
<%= form_for @photo_gallery, :url => path, :builder => TbCore::FormBuilder, :html => {:class => 'form-horizontal', :id => 'admin-photo-gallery-form'} do |f| %> 
  
  <%= tb_form_errors(f.object) %>
  
  <fieldset>
    <legend>Gallery Info</legend>  
      <%= f.tb_text_field :title %>
  </fieldset>
  
  <!-- if no albums are selected below, this ensures we send an empty album_ids array -->
  <%= hidden_field_tag 'spud_photo_gallery[album_ids][]' %>

  <fieldset>
    <legend>Select Albums</legend>

    <div class="row">
      <div class="col-md-8 admin-photo-album-column">
        <h4>Selected:</h4>
        <div class="admin-photo-ui-thumbs admin-photo-ui-thumbs-sortable">
          <%= render :partial => 'album', :collection => @photo_gallery.albums %>
        </div>
      </div>
      <div class="col-md-4 admin-photo-album-column">
        <h4>Available:</h4>
        <div class="admin-photo-ui-thumbs admin-photo-ui-thumbs-sortable admin-photo-albums-available">
          <%= render :partial => 'album', :collection => @photo_gallery.albums_available %>
        </div>
      </div>
    </div>
  </fieldset>

  <div class="row">
    <div class="col-md-12 admin-photo-album-column">
      <%= f.submit "Save Photo Gallery", :class => "btn btn-primary" %> 
      <%= link_to "Cancel", request.referer, :class => "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/admin/photo_galleries/destroy.js.erb
spud.admin.photos.markPhotoGalleryAsDeleted(<%= @photo_gallery.id %>);

app/views/admin/photo_galleries/edit.html.erb
<%= render :partial => 'form', :locals => {:path => admin_photo_gallery_path(@photo_gallery)} %>

app/views/admin/photo_galleries/index.html.erb
<%= content_for :data_controls do %>
  <%= link_to "New Photo Gallery", new_admin_photo_gallery_path, :class => "btn btn-primary", :title => "New Photo Gallery" %>
<% end %>

<%= content_for :detail do %>
  <div id="admin-photo-galleries" class="admin-photo-ui-thumbs">
    <% @photo_galleries.each do |gallery| %>
      <div id="admin-photo-gallery-<%= gallery.id %>" class="admin-photo-ui-thumb" style="background-image:url('<%= gallery.top_photo_url(:spud_admin_small) %>')">
        <h5><%= gallery.title %></h5>
        <div class="admin-photo-ui-thumb-controls">
          <%= link_to '', edit_admin_photo_gallery_path(gallery), :class => 'admin-photos-btn-edit' %>
          <%= link_to '', admin_photo_gallery_path(gallery), :method => :delete, :class => 'admin-photos-btn-delete', :remote => true, :data => {:confirm => 'Are you sure?'} %>
        </div>
      </div>
    <% end %>
  <div>
<% end %>

app/views/admin/photo_galleries/new.html.erb
<%= render :partial => 'form', :locals => {:path => admin_photo_galleries_path} %>