config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :photos do
      get 'library', :on => :collection
      post 'mass_destroy', :on => :collection
    end
    resources :photo_albums
    resources :photo_galleries
  end

  scope Spud::Photos.config.base_path do
    if Spud::Photos.config.galleries_enabled
      resources :photo_galleries, :only => :index, :path => '/' do
        resources :photo_albums, :only => [:index, :show], :path => '/'
      end
    else
      resources :photo_albums, :only => [:index, :show], :path => '/'
    end
  end

end

app/controllers/admin/photo_albums_controller.rb
class Admin::PhotoAlbumsController < Admin::ApplicationController

  before_filter :get_album, :only => [:show, :edit, :update, :destroy, :library]
  add_breadcrumb 'Photo Albums', :admin_photo_albums_path
  layout 'admin/spud_photos'
  belongs_to_spud_app :photo_albums

  def index
    @photo_albums = SpudPhotoAlbum.all
    respond_with @photo_albums
  end

  def show
    respond_with @photo_album
  end

  def new
    @photo_album = SpudPhotoAlbum.new
    respond_with @photo_album
  end

  def create
    @photo_album = SpudPhotoAlbum.new(photo_album_params)
    if @photo_album.save
      set_photo_order
    end
    respond_with @photo_album, :location => admin_photo_albums_path
  end

  def edit
    respond_with @photo_album
  end

  def update
    @photo_album.update_attributes(photo_album_params)
    if @photo_album.save
      set_photo_order
      flash[:notice] = 'Album updated successfully' 
    end
    respond_with @photo_album, :location => admin_photo_albums_path
  end

  def destroy
    flash.now[:notice] = 'Album deleted successfully' if @photo_album.destroy
    respond_with @photo_album, :location => admin_photo_albums_path
  end

  def get_album
    @photo_album = SpudPhotoAlbum.find(params[:id])
  end

private

  def set_photo_order
    order_ids = params[:spud_photo_album][:photo_ids] || []
    @photo_album.spud_photo_albums_photos.each do |obj|
      index = order_ids.index(obj.spud_photo_id.to_s)
      obj.update_attribute(:sort_order, index)
    end
  end

  def photo_album_params
    params.require(:spud_photo_album).permit(:title, :url_name, :photo_ids => [])
  end

end

app/controllers/photo_albums_controller.rb
class PhotoAlbumsController < ApplicationController

  respond_to :html, :json, :xml
  layout Spud::Photos.base_layout

  if Spud::Photos.galleries_enabled
    before_filter :get_gallery
  end

  def index
    if @photo_gallery
      @photo_albums = @photo_gallery.albums.ordered
    else
      @photo_albums = SpudPhotoAlbum.ordered
    end
    respond_with @photo_albums
  end

  def show
    @photo_album = SpudPhotoAlbum.find_by(:url_name => params[:id])
    if @photo_album.blank?
      raise Spud::NotFoundError.new(:item => 'photo album')
    else
      respond_with @photo_album
    end
  end

private

  def get_gallery
    @photo_gallery = SpudPhotoGallery.find_by(:url_name => params[:photo_gallery_id])
    if @photo_gallery.blank?
      raise Spud::NotFoundError.new(:item => 'photo gallery')
    end
  end

end

app/helpers/admin/photo_albums_helper.rb
module Admin::PhotoAlbumsHelper
end

app/helpers/photo_albums_helper.rb
module PhotoAlbumsHelper
end

app/views/photo_albums/index.html.erb
<% @page_title = @photo_gallery ? @photo_gallery.title : 'Photo Albums' %>

<% content_for :head do %>
  
<% end %>

<h2><%= (@photo_gallery ? "Photo Gallery: #{@photo_gallery.title}" : 'Photo Albums') %></h2>

<% if Spud::Photos.galleries_enabled %>
  <p><%= link_to 'Back to Galleries', photo_galleries_path %></p>
<% end %>

<% cache([@photo_gallery, @photo_albums]) do %>
  <div class="photo-albums">
    <% @photo_albums.each do |album| %>
      <div class="photo-album-thumbnail">
        <h3>
          <%= link_to album.title, (@photo_gallery ? photo_gallery_photo_album_path(@photo_gallery.url_name, album.url_name) : photo_album_path(album.url_name)) %>
        </h3>
        <%= image_tag album.top_photo_url(:medium), :title => album.title %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photo_albums/show.html.erb
<% @page_title = @photo_album.title %>

<% content_for :head do %>

<% end %>

<h2>Photo Album: <%= @photo_album.title %></h2>

<% cache(@photo_album) do %>
  <% if @photo_gallery %>
    <p><%= link_to 'Back to Albums', photo_gallery_photo_albums_path(@photo_gallery.url_name) %>
  <% else %>
    <p><%= link_to 'Back to Albums', photo_albums_path %>
  <% end %>

  <div class="photo-galleries">
    <% @photo_album.photos.each do |photo| %>
      <div class="photo-album-thumbnail">
        <%= link_to image_tag(photo.photo.url(:small), :alt => photo.caption, :title => photo.title), photo.photo.url(:large) %>
      </div>
    <% end %>
  </div>
<% end %>