config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :photos do
      get 'library', :on => :collection
      post 'mass_destroy', :on => :collection
    end
    resources :photo_albums
    resources :photo_galleries
  end

  scope Spud::Photos.config.base_path do
    if Spud::Photos.config.galleries_enabled
      resources :photo_galleries, :only => :index, :path => '/' do
        resources :photo_albums, :only => [:index, :show], :path => '/'
      end
    else
      resources :photo_albums, :only => [:index, :show], :path => '/'
    end
  end

end

app/models/spud_photo.rb
class SpudPhoto < ActiveRecord::Base

  extend ActionView::Helpers::NumberHelper

  has_many :spud_photo_albums_photos, :dependent => :destroy
  has_many :albums,
    :through => :spud_photo_albums_photos,
    :source => :spud_photo_album

  has_attached_file :photo, 
    :styles => lambda { |attachment| attachment.instance.dynamic_styles },
    :convert_options => Spud::Photos.convert_options,
    :source_file_options => Spud::Photos.source_file_options,
    :storage => Spud::Photos.paperclip_storage,
    :s3_credentials => Spud::Photos.s3_credentials,
    :url => Spud::Photos.storage_url,
    :path => Spud::Photos.storage_path

  validates_attachment :photo,
    :presence => true,
    :content_type => {:content_type => ['image/jpg', 'image/jpeg', 'image/png']},
    :size => {
      :less_than => Spud::Photos.max_image_upload_size,
      :message => "size cannot exceed " + number_to_human_size(Spud::Photos.max_image_upload_size), 
      :if => Proc.new{|p| Spud::Photos.max_image_upload_size > 0}
    }

  def dynamic_styles
    admin_styles = {
      :spud_admin_small => {:geometry => '125x125#', :format => :jpg, :source_file_options => '-density 72', :convert_options => '-strip -quality 85'},
      :spud_admin_medium => {:geometry => '300x200', :format => :jpg, :source_file_options => '-density 72', :convert_options => '-strip -quality 85'}
    }
    return admin_styles.merge(Spud::Photos.config.photo_styles)
  end

end

app/controllers/admin/photo_albums_controller.rb
class Admin::PhotoAlbumsController < Admin::ApplicationController

  before_filter :get_album, :only => [:show, :edit, :update, :destroy, :library]
  add_breadcrumb 'Photo Albums', :admin_photo_albums_path
  layout 'admin/spud_photos'
  belongs_to_spud_app :photo_albums

  def index
    @photo_albums = SpudPhotoAlbum.all
    respond_with @photo_albums
  end

  def show
    respond_with @photo_album
  end

  def new
    @photo_album = SpudPhotoAlbum.new
    respond_with @photo_album
  end

  def create
    @photo_album = SpudPhotoAlbum.new(photo_album_params)
    if @photo_album.save
      set_photo_order
    end
    respond_with @photo_album, :location => admin_photo_albums_path
  end

  def edit
    respond_with @photo_album
  end

  def update
    @photo_album.update_attributes(photo_album_params)
    if @photo_album.save
      set_photo_order
      flash[:notice] = 'Album updated successfully' 
    end
    respond_with @photo_album, :location => admin_photo_albums_path
  end

  def destroy
    flash.now[:notice] = 'Album deleted successfully' if @photo_album.destroy
    respond_with @photo_album, :location => admin_photo_albums_path
  end

  def get_album
    @photo_album = SpudPhotoAlbum.find(params[:id])
  end

private

  def set_photo_order
    order_ids = params[:spud_photo_album][:photo_ids] || []
    @photo_album.spud_photo_albums_photos.each do |obj|
      index = order_ids.index(obj.spud_photo_id.to_s)
      obj.update_attribute(:sort_order, index)
    end
  end

  def photo_album_params
    params.require(:spud_photo_album).permit(:title, :url_name, :photo_ids => [])
  end

end

app/controllers/photo_albums_controller.rb
class PhotoAlbumsController < ApplicationController

  respond_to :html, :json, :xml
  layout Spud::Photos.base_layout

  if Spud::Photos.galleries_enabled
    before_filter :get_gallery
  end

  def index
    if @photo_gallery
      @photo_albums = @photo_gallery.albums.ordered
    else
      @photo_albums = SpudPhotoAlbum.ordered
    end
    respond_with @photo_albums
  end

  def show
    @photo_album = SpudPhotoAlbum.find_by(:url_name => params[:id])
    if @photo_album.blank?
      raise Spud::NotFoundError.new(:item => 'photo album')
    else
      respond_with @photo_album
    end
  end

private

  def get_gallery
    @photo_gallery = SpudPhotoGallery.find_by(:url_name => params[:photo_gallery_id])
    if @photo_gallery.blank?
      raise Spud::NotFoundError.new(:item => 'photo gallery')
    end
  end

end

app/helpers/admin/photo_albums_helper.rb
module Admin::PhotoAlbumsHelper
end

app/helpers/photo_albums_helper.rb
module PhotoAlbumsHelper
end

app/views/admin/photo_albums/_album.html.erb
<div id="admin-photo-album-<%= album.id %>" class="admin-photo-ui-thumb" style="background-image:url('<%= album.top_photo_url(:spud_admin_small) %>')">
  <h5><%= album.title %></h5>
  <div style="display:none;">
    <%= hidden_field_tag 'spud_photo_gallery[album_ids][]', album.id %>
  </div>
  <div class="admin-photo-ui-thumb-controls">
    <%= link_to '', edit_admin_photo_album_path(album), :class => 'admin-photos-btn-edit' %>
    <%= link_to '', admin_photo_album_path(album), :method => :delete, :class => 'admin-photos-btn-delete', :remote => true, :data => {:confirm => 'Are you sure?'} %>
  </div>
</div>

app/views/admin/photo_albums/_form.html.erb
<%= form_for @photo_album, :url => path, :builder => TbCore::FormBuilder, :html => {:class => 'form-horizontal', :id => 'admin-photo-album-form'} do |f| %> 
  
  <%= tb_form_errors(f.object) %>

  <fieldset>
    <legend>Photo Album Info</legend>  
    <%= f.tb_text_field :title %>  
  </fieldset>

  <fieldset>
    <legend>Selected Photos</legend>

    <div class="row">
      <div class="col-md-12 admin-photo-album-column">
        <%= link_to "Photo Library", admin_photos_path, :class => "btn btn-sm btn-primary", :id => 'admin-photo-album-action-library' %>
        <%= link_to "Upload Photo", new_admin_photo_path, :class => "btn btn-sm btn-success", :id => 'admin-photo-album-action-upload' %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8 admin-photo-album-column">
        <div id="admin-photos-selected" class="control-group admin-photo-ui-thumbs admin-photo-ui-thumbs-sortable">
          <%= render :partial => '/admin/photos/photo', :collection => @photo_album.photos %>
        </div>
      </div>

      <div class="col-md-4 admin-photo-album-column">
        <div id="admin-photo-upload-queue">
          <p>Drag and drop photos here to upload</p>
          <h5 id="admin-photo-upload-queue_label">Queued Uploads: <span>0</span></h5>
          <div id="admin-photo-upload-queue_bars"></div>
        </div>
      </div>

    </div>
  </fieldset>

  <div class="row">
    <div class="col-md-12 admin-photo-album-column">
      <%= f.submit "Save Photo Album", :class=>"btn btn-primary" %> 
      <%= link_to "Cancel", request.referer, :class => "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/admin/photo_albums/destroy.js.erb
spud.admin.photos.markPhotoAlbumAsDeleted(<%= @photo_album.id %>);

app/views/admin/photo_albums/edit.html.erb
<%= render :partial => 'form', :locals => {:path => admin_photo_album_path(@photo_album)} %>

app/views/admin/photo_albums/index.html.erb
<%= content_for :data_controls do %>
  <%= link_to "New Photo Album", new_admin_photo_album_path, :class => "btn btn-primary", :title => "New Photo Album" %>
<% end %>

<%= content_for :detail do %>
  <div id="admin-photo-galleries" class="admin-photo-ui-thumbs">
    <%= render :partial => 'album', :collection => @photo_albums %>
  <div>
<% end %>

app/views/admin/photo_albums/new.html.erb
<%= render :partial => 'form', :locals => {:path => admin_photo_albums_path} %>